steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'GOOGLE_CREDENTIALS=$(cat google-credentials.json)'
      - '-t'
      - 'gcr.io/modern-bond-303506/train_image:latest'
      - '.'