steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - '_GIT_KEY=${_GIT_KEY}'
      - '--build-arg'
      - '_WANDB_KEY=${_WANDB_KEY}'
      - '--build-arg'
      - '_WANDB_KEY=${_SERVICE_ACCOUNT_KEY}'
      - '-t'
      - 'gcr.io/modern-bond-303506/train_image:latest'
      - '.'
substitutions:
  _GIT_KEY: 'default_git_key'
  _WANDB_KEY: 'default_wandb_key'
  _SERVICE_ACCOUNT_KEY: 'default_google_json'