stages:
  prepare:
    cmd: python data_loader.py data/all_data data/prepared
    deps:
      - data/all_data
      - data_loader.py
    params:
      - prepare
      - data
      - train
    outs:
      - data/prepared

  train:
    cmd: python train.py data/prepared model_versions
    deps:
      - data/prepared
      - train.py
    params:
      - train
      - model
    outs:
      - model_versions

  evaluate:
    cmd: python evaluate.py model_versions data/prepared evaluation_outputs
    deps:
      - data/prepared
      - evaluate.py
      - model_versions
    metrics:
      - evaluation_outputs/metrics.json
    plots:
      - evaluation_outputs/loss_curve.png
      - evaluation_outputs/confusion_matrix.png
      - evaluation_outputs/normalized_confusion_matrix.png