stages:
  prepare:
    cmd: python data_loader.py data/all_data data/prepared
    deps:
      - data/all_data
      - data_loader.py
    outs:
      - data/prepared
    params:
      - prepare
      - data
      - train

  train:
    cmd: python train.py data/prepared model_versions
    deps:
      - data/prepared
      - train.py
    params:
      - train
      - model

  evaluate:
    cmd: python evaluate.py model_versions data/prepared evaluation_outputs
    deps:
      - data/prepared
      - evaluate.py
      - model_versions