prepare:
  seed: 42
  split: 0.3  # 1 - train_split
  image_size: 224 
  sample_fraction: 0.85 # entre 0 et 1
  excluded_classes: #voir category_counts.txt
    - sky surfing
    - ultimate
    - wingsuit flying
    - arm wrestling
    - horseshoe pitching
    - water cycling
    - wheelchair basketball
    - baton twirling
    - hydroplane racing
  max_images_per_class: 120 #voir category_counts.txt

train:
  seed: 42
  lr: 0.0006
  epochs: 2
  batch_size: 2
  num_classes: 2 # minimum 1 jusqu'à 100 (soustraire excluded_classes)
  num_folds: 5 # minimum 2 sinon erreur (cross-validation)

model:
  name: google/efficientnet-b0

data:
  dir: ./data/all_data
