name: MLOps

on:
  push:
    branches:
      - dev

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      GIT_KEY: ${{ secrets.GIT_KEY }}
      WANDB_KEY: ${{ secrets.WANDB_KEY }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Activate Service Account
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > service-account-key2.json
          gcloud auth activate-service-account --key-file="service-account-key2.json"
      - name: List files
        run: ls -la

      - name: Configure gcloud
        run: gcloud config set project modern-bond-303506

      - name: Check GCS Bucket Access
        run: |
          echo "Testing GCS access..."
          gsutil ls gs://sportify_classifier || echo "Bucket access failed"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate service account key JSON
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" | base64 -d | jq .

      - name: Build and push Docker image
        run: |
          echo "Building Docker image and pushing to GCR..."
          SERVICE_ACCOUNT_KEY_BASE64=$(echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" | base64 -w 0)
          gcloud builds submit . \
            --config=cloudbuild.yaml \
            --substitutions=_GIT_KEY=$GIT_KEY,_WANDB_KEY=$WANDB_KEY,_SERVICE_ACCOUNT_KEY=$SERVICE_ACCOUNT_KEY_BASE64

      - name: Launch Vertex AI job
        id: launch_job
        run: |
          JOB_ID=$(gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name="entraînement-mlops" \
          --worker-pool-spec=machine-type=n1-standard-4,container-image-uri=gcr.io/modern-bond-303506/train_image:latest \
          --service-account=sportify-classier@modern-bond-303506.iam.gserviceaccount.com \
          --format='value(name)')
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      - name: Wait for job to finish
        run: |
          STATUS=$(gcloud ai custom-jobs describe "${JOB_ID}" --region=us-central1 --format='value(state)')
          MAX_RETRIES=60
          COUNT=0
          while [ "$STATUS" != "JOB_STATE_SUCCEEDED" ] && [ "$STATUS" != "JOB_STATE_FAILED" ] && [ $COUNT -lt $MAX_RETRIES ]; do
            echo "Job status: $STATUS"
            gcloud logging read "resource.type=ml_job AND resource.labels.job_id=\"${JOB_ID}\"" --limit=50 --format="value(textPayload)"
            sleep 30
            STATUS=$(gcloud ai custom-jobs describe "${JOB_ID}" --region=us-central1 --format='value(state)')
            COUNT=$((COUNT + 1))
          done

          if [ "$STATUS" = "JOB_STATE_FAILED" ]; then
            echo "Job failed. Detailed logs:"
            gcloud logging read "resource.type=ml_job AND resource.labels.job_id=\"${JOB_ID}\"" \
              --limit=100 --format="value(textPayload)"
            exit 1
          elif [ $COUNT -ge $MAX_RETRIES ]; then
            echo "Job did not finish within the expected time."
            exit 1
          fi

        env:
          JOB_ID: ${{ env.JOB_ID }}

      - name: Pull evaluation_output from GCS
        run: |
          mkdir -p ./evaluation_output
          gsutil -m cp -r "gs://sportify_classifier/evaluation_output/*" ./evaluation_output
          ls -la ./evaluation_output

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SECRET }}
          commit-message: "Automated results from dev branch"
          branch: dev
          base: main
          title: "Merge dev into main - Evaluation Results"
          body: |
            [Compare les modèles sur Weights & Biases](https://wandb.ai/sportify/sports-classification)
            Veuillez examiner les résultats et décider si ce modèle doit être fusionné dans la branche principale (`main`).
          draft: false