name: MLOps

on:
  push:
    branches:
      - dev

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Activer le compte de service avec le fichier service-account-key.json
      - name: Activate Service Account
        run: |
          gcloud auth activate-service-account --key-file="service-account-key.json"

      - name: List files in context
        run: ls -la

      # Configurer le projet GCP
      - name: Configure gcloud
        run: gcloud config set project modern-bond-303506

      # Vérifier les permissions sur le bucket
      - name: Check GCS Bucket Access
        run: |
          echo "Testing GCS access..."
          gsutil ls gs://sportify_classifier || echo "Bucket access failed, ensure credentials and permissions are correct"
      

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Construire l'image Docker et la pousser sur GCR
      - name: Build and push Docker image
        run: |
          echo "Building Docker image and pushing to GCR..."
          cat service-account-key.json | jq .
          export SERVICE_ACCOUNT_KEY_BASE64=$(cat service-account-key.json | base64 -w 0)
          gcloud builds submit . \
          --config=cloudbuild.yaml \
      # Construire l'image Docker et la pousser sur GCR
      - name: Build and push Docker image
        run: |
          echo "Building Docker image and pushing to GCR..."
          export SERVICE_ACCOUNT_KEY_BASE64=$(cat service-account-key.json | base64 -w 0)
          gcloud builds submit . \
          --config=cloudbuild.yaml \
          --substitutions=_GIT_KEY=${{ secrets.GIT_KEY }},_WANDB_KEY=${{ secrets.WANDB_KEY }},_SERVICE_ACCOUNT_KEY=${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}

      # Lancer le job Vertex AI
      - name: Launch Vertex AI job
        id: launch_job
        run: |
          echo "Launching Vertex AI Job..."
          JOB_ID=$(gcloud ai custom-jobs create \
          --region=us-central1 \
          --display-name="entraînement-mlops" \
          --worker-pool-spec=machine-type=n1-standard-4,container-image-uri=gcr.io/modern-bond-303506/train_image:latest \
          --service-account=sportify-classier@modern-bond-303506.iam.gserviceaccount.com \
          --format='value(name)')
          echo "Vertex AI Job ID: $JOB_ID"
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      # Attendre la fin du job Vertex AI
      - name: Wait for job to finish
        run: |
          echo "Waiting for Vertex AI Job to finish..."
          STATUS=$(gcloud ai custom-jobs describe "${JOB_ID}" --region=us-central1 --format='value(state)')
          MAX_RETRIES=60 
          COUNT=0
          while [ "$STATUS" != "JOB_STATE_SUCCEEDED" ] && [ "$STATUS" != "JOB_STATE_FAILED" ] && [ $COUNT -lt $MAX_RETRIES ]; do
            echo "Job status: $STATUS"
            echo "Fetching logs for Job ID: ${JOB_ID}..."
            gcloud logging read "resource.type=ml_job AND resource.labels.job_id=\"${JOB_ID}\"" --limit=50 --format="value(textPayload)"
            sleep 30
            STATUS=$(gcloud ai custom-jobs describe "${JOB_ID}" --region=us-central1 --format='value(state)')
            COUNT=$((COUNT + 1))
          done

          echo "Final job status: $STATUS"
          if [ "$STATUS" = "JOB_STATE_FAILED" ]; then
            echo "Fetching detailed logs for failure..."
            gcloud logging read "resource.type=ml_job AND resource.labels.job_id=\"${JOB_ID}\"" --limit=100 --format="value(textPayload)"
            exit 1
          elif [ $COUNT -ge $MAX_RETRIES ]; then
            echo "Job did not finish within the expected time."
            exit 1
          fi
        env:
          JOB_ID: ${{ env.JOB_ID }}

      # Récupérer les résultats depuis GCS
      - name: Pull evaluation_output from GCS
        run: |
          echo "Ensuring local evaluation_output directory exists..."
          mkdir -p ./evaluation_output
          echo "Fetching evaluation_output from GCS..."
          gsutil -m cp -r "gs://sportify_classifier/evaluation_output/*" ./evaluation_output
          echo "Listing downloaded files..."
          ls -la ./evaluation_output
      
      # Créer une Pull Request pour fusionner `dev` dans `main`
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SECRET }}
          commit-message: "Automated results from dev branch"
          branch: dev
          base: main
          title: "Merge dev into main - Evaluation Results"
          body: |
            [Compare les modèles sur Weights & Biases](https://wandb.ai/sportify/sports-classification)
            Veuillez examiner les résultats et décider si ce modèle doit être fusionné dans la branche principale (`main`). Les graphiques et résultats détaillés sont inclus dans cette PR.
          draft: false # Set to true if you want to create the PR as a draft
