name: MLOps Main

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      GIT_KEY: ${{ secrets.GIT_KEY }}
      WANDB_KEY: ${{ secrets.WANDB_KEY }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Check the connect to gcloud, but unfortunately, we didn't find the solution to put a secret.
      - name: Activate Service Account
        run: |
          gcloud auth activate-service-account --key-file="service-account-key.json"

      # For debugging
      - name: List files in context
        run: ls -la

      # set the project
      - name: Configure gcloud
        run: gcloud config set project modern-bond-303506

      - name: Set up the project With DVC
        run: dvc repro --pull

      - name: Pull the latest BentoML model with DVC
        run: |
          LATEST_MODEL_DIR=$(ls -td model_versions/model_* | head -n 1)
          echo "Le dernier modèle trouvé est : $LATEST_MODEL_DIR"

          dvc pull $LATEST_MODEL_DIR
          bentoml models import ${LATEST_MODEL_DIR}/sports_classifier_model.bentomodel

      - name: Validate BentoML Models
        run: bentoml models list

      - name: Authenticate Docker to Artifact Registry
        run: gcloud auth configure-docker europe-west6-docker.pkg.dev

      - name: Clean up space
        run: |
          echo "Libération d'espace disque"
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet /usr/share/swift
          docker system prune -af
          docker volume prune -f
          df -h

      - name: Build BentoML Container
        include:
          - serve.py
          - templates/**
        run: |
          pip install bentoml==1.3.16 Flask==3.1.0 pillow==11.0.0 torch==2.5.1 transformers==4.47.0
          bentoml build --bentofile bentofile.yaml
          bentoml containerize sports_classifier_service:latest \
            --image-tag europe-west6-docker.pkg.dev/modern-bond-303506/mlops-sportify-classifier/sports-classifier:latest \
            --image-tag europe-west6-docker.pkg.dev/modern-bond-303506/mlops-sportify-classifier/sports-classifier:${{ github.sha }}

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push --all-tags europe-west6-docker.pkg.dev/modern-bond-303506/mlops-sportify-classifier/sports-classifier

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sports-classifier-service \
              --image europe-west6-docker.pkg.dev/modern-bond-303506/mlops-sportify-classifier/sports-classifier:latest \
              --platform managed \
              --region europe-west6 \
              --allow-unauthenticated \
              --memory 8Gi \
              --concurrency 10